services:
  backend:
    build: ./backend
    container_name: django_dash
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env


  frontend:
    build: ./frontend
    container_name: react_dash
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api
      - VITE_DEV_PORT=5173
    depends_on:
      - backend

